package letenky;

public enum Stav {
	START, REGISTRACIAMENO, REGISTRACIAPRIEZVISKO, REGISTRACIAADRESA, VYBERLET, VYBERDRUHLETU, VYBERTYPLETU,
	VYBERTRIEDU, VYBERSEDADLO, OBSADENESEDADLO, VYPLNMENOLETENKY, POKRACUJZAPLATIT, ZAPLATIT, ZRUSENIEREGISTRACIE, ZRUSITIDREGISTRACIE, REGISTRACIAZRUSENA, KONIECPROGRAMU
}
