package letenky;

public enum Stav {
	START, REGISTRACIAMENO, REGISTRACIAPRIEZVISKO, REGISTRACIAADRESA, VYBERLET, VYBERDRUHLETU, VYBERTYPLETU,
	VYBERTRIEDU, VYBERSEDADLO, VYPLNMENOLETENKY, NEVYPLNENEMENO, OBSADENESEDADLO, POKRACUJKONIEC, ZRUSENIEREGISTRACIE, IDREGISTRACIE, REGISTRACIAZRUSENA, KONIECPROGRAMU
}
